/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function _setup_console_error(): void;
export function vmstore_init(a: number, b: number, c: number): number;
export function vmstore_get(a: number, b: number): number;
export function vmstore_destroy(a: number, b: number): void;
export function vmstore_ids(a: number): void;
export function __wbg_virtualmachine_free(a: number): void;
export function virtualmachine_valid(a: number): number;
export function virtualmachine_assert_valid(a: number, b: number): void;
export function virtualmachine_destroy(a: number, b: number): void;
export function virtualmachine_addToScope(a: number, b: number, c: number, d: number, e: number): void;
export function virtualmachine_setStdout(a: number, b: number, c: number): void;
export function virtualmachine_injectModule(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function virtualmachine_injectJSModule(a: number, b: number, c: number, d: number, e: number): void;
export function virtualmachine_exec(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function virtualmachine_eval(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function virtualmachine_execSingle(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function pyEval(a: number, b: number, c: number, d: number): void;
export function pyExec(a: number, b: number, c: number, d: number): void;
export function pyExecSingle(a: number, b: number, c: number, d: number): void;
export function __wbg_vmstore_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke1__h735a099dd21751b8(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function wasm_bindgen__convert__closures__invoke2_mut__ha540feaed8fe3c1f(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h8fda2679c5188379(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5318a7b8877a6360(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h2fdb17aed727f2e1(a: number, b: number, c: number, d: number): void;
export function __wbindgen_start(): void;
